storage: ./storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@content-island/nuxt':
    access: $anonymous
    publish: $anonymous
  '**':
    access: $anonymous
    publish: $anonymous
    proxy: npmjs
